### ISSUE TITLE
Joker 2.1.4 bug display

### ISSUE THREAD

**Issue by xela13** [Phonations/Joker#410]
Par rapport à la v2.0.0, la vidéo et la rythmo saccadent énormément voir quasi tout le temps. La v2.0.0 était plus stable.

**Comment by MartinDelille** [comment]
Duplicate #398

**Comment by MartinDelille** [comment]
Pouvez-vous me dire quel type de machine vous utilisez?

**Comment by xela13** [comment]
Operating System: Microsoft Windows 7 Home Premium (x64) Build 7601
CPU / INTEL CORE I3-2100 3.10GHZ
RAM 8GO
Video Card: Intel Sandy Bridge-DT GT1 - Integrated Graphics Controller [D2/J1/Q0] [GIGABYTE] + 
Video Card: PNY Verto GeForce GT 610
