### ISSUE TITLE
.detx rythmo and video out of sync

### ISSUE THREAD

**Issue by ApolloLegacy** [Phonations/joker#428]
Hi, I've been using Joker (2.1.3 W10 64bits) for quite some time but recently I encounter an issue.

For editing rythmo bands, I use Capella. Then, as I think Joker is better visually, I import my .detx project into Joker. But, even if the rythmo is perfectly in sync into Capella, and the timestamp is correct in Joker, the video is out of sync.

**Comment by MartinDelille** [comment]
Can you click _File > Properties..._ and take a screenshot of the pop up window?

**Comment by ApolloLegacy** [comment]
Yep, there it is https://m.imgur.com/03i07Sv

**Comment by MartinDelille** [comment]
Can you do the same from QuickTime or vlc?

**Comment by ApolloLegacy** [comment]
Here's what VLC say : http://imgur.com/PZ95uWb

**Comment by MartinDelille** [comment]
Ok this problem will be solved in the next version.

**Comment by MartinDelille** [comment]
Can you test if it works with this intermediate version? https://ci.appveyor.com/api/buildjobs/jtgwepd0iig5rnm6/artifacts/Joker_v2.1.4.98.exe

**Comment by ApolloLegacy** [comment]
It works like a charm, thank you !
